### ISSUE TITLE
Before the HOL

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Big-Compute#5]
I renamed the document & updated to current template but I don't know how to format a table of contents yet.  Please add that section to the doc.

**Comment by ZoinerTejada** [comment]
Our other Before the HOL documents do not have a ToC. I believe adding this would create an inconsistency, please confirm and we can re-open if a ToC is what we want to add as a new thing to the other Before the HOL docs.

**Comment by DawnmarieDesJardins** [comment]
Reopening issues as TOCs are now required on all Before the HOL documents.  This issue can be address now, or with the next test/fix or update.
Thank you!

**Comment by kylebunting** [comment]
Added TOC to Before the HOL document in the September 2018 test-fix.
