### ISSUE TITLE
HOL - step by step

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Big-Compute#6]
Please take a look at the formatting on lines 748 - 757 (Exercise 3, task 1, step 2).  I'm not sure it's formatting the way you want it to when I look from the code to the document.

Same with step 3 - should those be indented??

Step 6 says:  This means the VM nodes in the pool are ready for some work.  Continue with the next task to supply some … ?

**Comment by ZoinerTejada** [comment]
These have been verified and fixed (where appropriate) in commit 93532ce.
